<?php

namespace Database\Seeders;

use App\Models\Mou;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class MouSeeder extends Seeder
{
    public function run(): void
    {
        $mous = [
            [
                'mou_number' => 'MOU/UMMADA/001/2024',
                'title' => 'Kerjasama Tri Dharma Perguruan Tinggi',
                'institution_id' => 1,
                'category_id' => 1,
                'level' => 'nasional',
                'type' => 'akademik',
                'cooperation_type' => 'mou',
                'faculty_id' => 1,
                'pic_name' => 'Dr. Ahmad Fauzi',
                'pic_email' => 'ahmad.fauzi@ummada.ac.id',
                'start_date' => '2024-01-15',
                'end_date' => '2027-01-15',
                'duration_months' => 36,
                'status' => 'aktif',
                'visibility' => 'public',
                'description' => 'Kerjasama di bidang pendidikan, penelitian, dan pengabdian masyarakat.',
                'public_summary' => 'Kerjasama komprehensif dengan UI dalam bidang Tri Dharma Perguruan Tinggi.',
                'created_by' => 1,
            ],
            [
                'mou_number' => 'MOU/UMMADA/002/2024',
                'title' => 'Program Magang Merdeka Belajar',
                'institution_id' => 4,
                'category_id' => 4,
                'level' => 'nasional',
                'type' => 'mbkm',
                'cooperation_type' => 'moa',
                'faculty_id' => 1,
                'pic_name' => 'Ir. Budi Santoso',
                'pic_email' => 'budi@telkom.co.id',
                'start_date' => '2024-03-01',
                'end_date' => '2026-03-01',
                'duration_months' => 24,
                'status' => 'aktif',
                'visibility' => 'public',
                'description' => 'Program MBKM magang di PT Telkom Indonesia.',
                'public_summary' => 'Program magang bersertifikat untuk mahasiswa UMMADA di Telkom Indonesia.',
                'created_by' => 1,
            ],
            [
                'mou_number' => 'MOU/UMMADA/003/2023',
                'title' => 'Pertukaran Mahasiswa Internasional',
                'institution_id' => 6,
                'category_id' => 5,
                'level' => 'internasional',
                'type' => 'internasional',
                'cooperation_type' => 'mou',
                'faculty_id' => null,
                'pic_name' => 'Prof. Dr. Siti Aisyah',
                'pic_email' => 'siti.aisyah@ummada.ac.id',
                'start_date' => '2023-08-01',
                'end_date' => '2026-08-01',
                'duration_months' => 36,
                'status' => 'aktif',
                'visibility' => 'public',
                'description' => 'Program pertukaran mahasiswa antara UMMADA dan Universiti Malaya.',
                'public_summary' => 'Pertukaran mahasiswa dan dosen dengan Universiti Malaya, Malaysia.',
                'created_by' => 1,
            ],
            [
                'mou_number' => 'MOU/UMMADA/004/2023',
                'title' => 'Praktik Kerja Lapangan Keperawatan',
                'institution_id' => 8,
                'category_id' => 3,
                'level' => 'lokal',
                'type' => 'akademik',
                'cooperation_type' => 'pks',
                'faculty_id' => 5,
                'pic_name' => 'Ns. Dewi Rahayu, M.Kep',
                'pic_email' => 'dewi@ummada.ac.id',
                'start_date' => '2023-06-01',
                'end_date' => Carbon::now()->addDays(45)->format('Y-m-d'),
                'duration_months' => 24,
                'status' => 'akan_expire',
                'visibility' => 'public',
                'description' => 'Praktik kerja lapangan mahasiswa keperawatan di RSUD Cirebon.',
                'public_summary' => 'PKL mahasiswa keperawatan UMMADA di RSUD Cirebon.',
                'created_by' => 1,
            ],
            [
                'mou_number' => 'MOU/UMMADA/005/2022',
                'title' => 'Penelitian Bersama Ekonomi Syariah',
                'institution_id' => 9,
                'category_id' => 2,
                'level' => 'nasional',
                'type' => 'penelitian',
                'cooperation_type' => 'mou',
                'faculty_id' => 4,
                'pic_name' => 'Dr. Muhammad Hidayat',
                'pic_email' => 'hidayat@ummada.ac.id',
                'start_date' => '2022-09-01',
                'end_date' => Carbon::now()->subDays(30)->format('Y-m-d'),
                'duration_months' => 24,
                'status' => 'expire',
                'visibility' => 'internal',
                'description' => 'Penelitian bersama di bidang ekonomi syariah dengan BSI.',
                'public_summary' => null,
                'created_by' => 1,
            ],
            [
                'mou_number' => 'MOU/UMMADA/006/2024',
                'title' => 'Kerjasama Pendidikan Guru Profesional',
                'institution_id' => 5,
                'category_id' => 6,
                'level' => 'lokal',
                'type' => 'pemerintah',
                'cooperation_type' => 'mou',
                'faculty_id' => 3,
                'pic_name' => 'Drs. Hendra Wijaya, M.Pd',
                'pic_email' => 'hendra@ummada.ac.id',
                'start_date' => '2024-02-01',
                'end_date' => '2027-02-01',
                'duration_months' => 36,
                'status' => 'aktif',
                'visibility' => 'public',
                'description' => 'Program peningkatan kualitas guru di wilayah Cirebon.',
                'public_summary' => 'Kolaborasi peningkatan mutu pendidikan dengan Dinas Pendidikan Kota Cirebon.',
                'created_by' => 1,
            ],
            [
                'mou_number' => 'MOU/UMMADA/007/2024',
                'title' => 'Program Riset Teknologi Informasi',
                'institution_id' => 2,
                'category_id' => 8,
                'level' => 'nasional',
                'type' => 'penelitian',
                'cooperation_type' => 'mou',
                'faculty_id' => 1,
                'pic_name' => 'Dr. Agus Prasetyo',
                'pic_email' => 'agus@ummada.ac.id',
                'start_date' => '2024-05-01',
                'end_date' => '2026-05-01',
                'duration_months' => 24,
                'status' => 'aktif',
                'visibility' => 'public',
                'description' => 'Riset bersama di bidang kecerdasan buatan dan IoT.',
                'public_summary' => 'Kolaborasi riset teknologi dengan ITB di bidang AI dan IoT.',
                'created_by' => 1,
            ],
            [
                'mou_number' => 'MOU/UMMADA/008/2024',
                'title' => 'Pengabdian Masyarakat Desa Digital',
                'institution_id' => 10,
                'category_id' => 3,
                'level' => 'nasional',
                'type' => 'pengabdian',
                'cooperation_type' => 'pks',
                'faculty_id' => 1,
                'pic_name' => 'Dr. Rina Kartika',
                'pic_email' => 'rina@ummada.ac.id',
                'start_date' => '2024-04-01',
                'end_date' => '2025-04-01',
                'duration_months' => 12,
                'status' => 'aktif',
                'visibility' => 'public',
                'description' => 'Program digitalisasi desa mitra UMMADA.',
                'public_summary' => 'Pengabdian masyarakat digitalisasi desa bersama Yayasan Pendidikan Nusantara.',
                'created_by' => 1,
            ],
        ];

        foreach ($mous as $mou) {
            Mou::create($mou);
        }
    }
}
